[versions]
minecraft = "1.21.11"
minecraft-supported = "1.21.11"
parchment = "2025.10.12"

fabric-loom = "1.14-SNAPSHOT"
fabric-loader = "0.18.2"
fabric-api = "0.140.0+1.21.11"

creative = "817fa982c4"
packconverter = "3.4.1-20251013.173215-13"

[libraries]
minecraft = {group = "com.mojang", name = "minecraft", version.ref = "minecraft"}
parchment = {group = "org.parchmentmc.data", name = "parchment-1.21.10", version.ref = "parchment"}

fabric-loom = {group = "net.fabricmc", name = "fabric-loom", version.ref = "fabric-loom"}
fabric-loader = {group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader"}
fabric-api = {group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api"}

creative-api = {group = "com.github.GeyserMC.unnamed-creative", name = "creative-api", version.ref = "creative"}
creative-serializer-minecraft = {group = "com.github.GeyserMC.unnamed-creative", name = "creative-serializer-minecraft", version.ref = "creative"}
packconverter = {group = "org.geysermc.pack", name = "converter", version.ref = "packconverter"}

[plugins]
